name: flutter_kakaonavi_mlkit
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  # mlkit
  flutter_pdfview: ^1.3.3
  image_picker: ^1.1.2
  camera: ^0.10.6
  path: ^1.9.0
  path_provider: ^2.1.4
  audioplayers: ^6.1.0
  volume_controller: ^2.0.8
  haptic_feedback: ^0.5.1+1
  google_mlkit_commons: any
  google_mlkit_face_detection:
    path: google_mlkit_face_detection

  # kakao
  kakao_flutter_sdk_user: ^1.9.6
  kakao_flutter_sdk_navi: ^1.9.6
  http: ^1.2.2

  # foregound
  flutter_foreground_task: ^8.13.0
  flutter_overlay_window: ^0.4.5
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1

  # firebase
  firebase_core: ^3.8.0
  device_info_plus: ^11.1.1
  firebase_database: ^11.1.6


dependency_overrides:
  google_mlkit_commons:
    path: google_mlkit_commons

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
  - assets/kakao_login_large_narrow.png
  - assets/alarm.wav


